sudo: false
language: node_js
node_js:
  - stable
  - 6
  - 5
  - 4
after_success:
  - npm install codecov
  - ./node_modules/.bin/codecov
notifications:
  slack: about-hiroppy:rzKYJ3zRPzBaak3TeaTmPSH5
